[package]
name = "atto-desktop"
version = "0.1.0"
description = "Atto desktop application"
authors = ["Atto"]
edition = "2021"

[lib]
name = "atto_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[features]
custom-protocol = ["tauri/custom-protocol"]
